# f=open("harry2.text","a")
# f.write("harry bhau bhut ache hai  mahan hai")
# s=f.write("harry bhau bhut ache hai  mahan hai\n  ")
# p=f.write("thanku bhai")
# print(s)
# print(p)
# f=open("harry2.text","r")
# c=f.read()
# print(c)
# f.close()